spring:
  application:
    name: post-service
  # 数据源配置项
  datasource:
    url: jdbc:mysql://172.16.225.131:3306/lightflow_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Cc3-123456

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 本地开发环境下，多打印 SQL 到控制台
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.abmis.lightflow.postservice.dal.mysql.dataobject